### ISSUE TITLE
Console error spamming

### ISSUE THREAD

**Issue by pizzanakin** [Zazsona/DecorHeads#13]
The decorheads plugin is currently spamming my server's console with these errors.
`- [Sat 11:16:37 ERROR Minecraft] Could not pass event BlockPistonExtendEvent to DecorHeads v2.3.0
java.lang.NullPointerException: Cannot invoke "java.util.HashMap.get(Object)" because "this.blockMeta" is null
    at DecorHeads.jar//com.zazsona.decorheads.blockmeta.BlockMetaLogger.isMetadataSet(BlockMetaLogger.java:89)
    at DecorHeads.jar//com.zazsona.decorheads.blockmeta.BlockMetaLogger.isMetadataSet(BlockMetaLogger.java:102)
    at DecorHeads.jar//com.zazsona.decorheads.blockmeta.BlockMetaLogger.isMetadataSet(BlockMetaLogger.java:108)
    at DecorHeads.jar//com.zazsona.decorheads.blockmeta.BlockInventoryOwnerListener.onPistonExtend(BlockInventoryOwnerListener.java:124)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor52.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
    at net.minecraft.world.level.block.piston.BlockPiston.a(BlockPiston.java:392)
    at net.minecraft.world.level.block.piston.BlockPiston.a(BlockPiston.java:222)
    at net.minecraft.world.level.block.state.BlockBase$BlockData.a(BlockBase.java:949)
    at net.minecraft.server.level.WorldServer.a(WorldServer.java:1771)
    at net.minecraft.server.level.WorldServer.ar(WorldServer.java:1757)
    at net.minecraft.server.level.WorldServer.a(WorldServer.java:653)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619)
    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1482)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
    at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
    at java.base/java.lang.Thread.run(Thread.java:833)`

It started after my server experienced a crash so perhaps it's caused by some corrupt data?

**Comment by pizzanakin** [comment]
I've found the issue! our blockMetadata.json file indeed got corrupted, but luckily I have a backup that I can restore it with

**Comment by Zazsona** [comment]
Glad to hear you found the cause! Shame about the corruption though! That file tracks metadata for placed heads, so you might find heads newly placed between the back-up and the crash won't drop when broken! (If it's not already enabled, you can turn on the head-meta-patcher in the config which'll try and restore any lost head data when a head is broken! It may clash with other head plugins if they use the same head names though!)

For the next update DecorHeads metadata is stored per-chunk and within the world file, so should hopefully reduce the data loss if something like this occurs in future, and make DecorHeads better compatible with automatic world backup plugins!
