### ISSUE TITLE
Could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by Roan-V** [Zazsona/DecorHeads#3]
Hey!

Not sure if you've seen this before but decorheads throws some errors into the server console at times (assuming when somebody breaks a head, haven't had the time to test yet).

Full error here, seems like it's trying to parse float from a string that isn't set:

`[13:29:39 ERROR]: Could not pass event BlockBreakEvent to DecorHeads v1.5.1
java.lang.NumberFormatException: For input string: "null"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:543) ~[?:?]
        at com.zazsona.decorheads.Settings.getDropChance(Settings.java:89) ~[?:?]
        at com.zazsona.decorheads.HeadDropListener.dropHead(HeadDropListener.java:288) ~[?:?]
        at com.zazsona.decorheads.HeadDropListener.checkGlobalBlockDrops(HeadDropListener.java:77) ~[?:?]
        at com.zazsona.decorheads.HeadDropListener.onBlockBreak(HeadDropListener.java:48) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor71.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1078]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1078]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1078]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:392) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:345) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:305) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1765) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1335) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1304) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1148) ~[patched_1.16.5.jar:git-Purpur-1078]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1078]
        at java.lang.Thread.run(Thread.java:834) [?:?]`
        
Let me know if you need any other information

**Comment by Zazsona** [comment]
Hmm, interesting, cheers for posting! Do you have your config handy? Seems to be an issue with reading the drop chance for a certain block!

**Comment by Roan-V** [comment]
Hmm interesting, here:
[DecorHeadsconfig.txt](https://github.com/Zazsona/DecorHeads/files/6447784/DecorHeadsconfig.txt)

**Comment by Zazsona** [comment]
Thanks, I think I might've figured it out, haha.
I made a typo in the config template - `MiniCimsonStem` instead of `MiniCRimsonStem`! You should be able to stop the errors by changing that. I'll fix it for the next update!

**Comment by Roan-V** [comment]
Simple fix at least :P
Thanks!
